# Generated by Django 4.0.2 on 2022-11-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Profile', models.CharField(max_length=250)),
                ('URL', models.URLField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_desc', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(default=None, max_length=13)),
                ('email', models.EmailField(max_length=255)),
                ('Profile_image', models.ImageField(default='media/default.jpg', upload_to='media/')),
                ('dob', models.DateField(max_length=8)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('objctive', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companay_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('total_Experience', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Education', models.CharField(choices=[('SSC', 'Secondary School Certificate'), ('HSC', 'Higher Secondary School Certificate'), ('Graduation', 'Graduation')], max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Percentage', models.PositiveIntegerField()),
                ('Passing_Year', models.DateField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=20)),
                ('Marital_Status', models.CharField(choices=[('Single', 'Single/Unmarried'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Seprated', 'Seprated'), ('Other', 'Other')], max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('Language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Marathi', 'Marathi')], max_length=15)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
