# Generated by Django 4.0.2 on 2022-11-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='Profile_image',
            new_name='profile_picture',
        ),
    ]
