# Generated by Django 4.0.2 on 2022-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_id_additionalinfo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='education',
            name='Education',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Graduation', 'Graduation')], max_length=255),
        ),
    ]
