# Generated by Django 4.0.2 on 2022-11-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_id_education_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Name',
            new_name='institute',
        ),
    ]
