# Generated by Django 4.0.2 on 2022-11-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_education_education_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Passing_Year',
            new_name='passing_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Percentage',
            new_name='percentage',
        ),
    ]
