# Generated by Django 4.0.2 on 2022-11-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_passing_year_education_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
