# Generated by Django 4.0.2 on 2022-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_education_passing_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='companay_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.PositiveIntegerField(),
        ),
    ]
