# Generated by Django 4.0.2 on 2022-11-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_companay_name_experience_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialprofile',
            old_name='Social_Profile',
            new_name='social_profile',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='URL',
            new_name='url',
        ),
    ]
