# Generated by Django 4.0.2 on 2022-11-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_certification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='Marital_Status',
            new_name='marital_Status',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='total_Experience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AddField(
            model_name='experience',
            name='workingOn',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='sex',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=255),
        ),
    ]
