# Generated by Django 4.0.2 on 2022-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_language_additionalinfo_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
